---
title: Jules @ Waag
baseurl: "/home"
url: "haystackly.fr"
desc: A minimal blog for off-topic blog entries.
about: I'm a coding lizard.
image: https://pbs.twimg.com/profile_images/1079097017551462402/5Gz0T3et_400x400.jpg
excerpt_separator: "<!-- more -->"
markdown: kramdown
gems:
- jekyll-paginate
exclude:
  - .jekyll-metadata
  - README.md
  - CNAME
paginate: 20
paginate_path: "/:num/"
highlighter: rouge
permalink: pretty
